package features;

import constants.Constants;
import org.junit.AfterClass;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.sleep;

public class DeleteAllAutoUsers extends AdminLogin {

    @AfterClass
    public void deleteAllAgents() {
        if (Constants.DELETE_ALL_AUTOGENERATED_AGENTS) {
            $(By.xpath("//*[@id=\"agent-list-filters\"]/td[2]/input")).setValue("auto").pressEnter();
            $(By.xpath("//*[@id=\"agent-list\"]/div[2]/table/thead/tr[1]/th[1]/input")).click();
            $(By.xpath("//*[@id=\"agent-list\"]/div[1]/div/div/div[2]/a[1]")).click();
            sleep(50);
        }
    }
}
