package constants;

/**
 * Class contains common constants
 */
public final class Constants
{
    //need to login
    public static final Boolean CLEAR_CACHE_EACH_TEST = false;
    public static final Boolean NEED_TO_RELOGIN = false;

    //need to delete all auto agents
    public static final Boolean DELETE_ALL_AUTOGENERATED_AGENTS = false;

    //need to delete all auto properties
    public static final Boolean DELETE_ALL_AUTOGENERATED_PROPERTIES = false;
    //todo: make function



    //advantageu site locations
    public static final String SITE_AU_ADRESS = "https://advantageu.realagentpro.com";
    public static final String SITE_AU_ADMIN_SUBADRESS = "/admin";

    //credentials for AU admin
    public static final String SITE_AU_ADMIN_LOGIN = "superadmin@advantageu.com";
    public static final String SITE_AU_ADMIN_PASSWORD = "h}*,VC(T]bVW/=r]";

    private Constants()
    {
        //nothing. Constant archive class.
    }
}
